/**
 * Forced password change (D-06). Shown instead of the portal — for staff,
 * captains and admins alike — while the signed-in account's users row still
 * has must_change_password = true.
 *
 * WHY IT BLOCKS: the flag is set by manage-bhw when an account is created or
 * its password is reset, and the password it is set alongside was generated by
 * the system and read by whoever provisioned the account. Until the holder
 * replaces it, the provisioner can sign in as them. So this is not a dismissable
 * prompt: there is no "later", and the only way past it is setting a password
 * or signing out.
 *
 * WHAT IT IS NOT: enforcement. The flag is cleared by an RPC the client calls
 * after auth.updateUser() succeeds (migration 0019 — clients have no UPDATE
 * grant on the column since 0017), and the database cannot verify the password
 * really changed. Someone driving the API directly could skip this. That is
 * accepted: the account being protected is their own, and what the gate closes
 * is the provisioner's standing access, which no client-side trick reopens.
 *
 * It reuses LoginLayout so a blocked account gets the same brand panel and
 * language pills as the sign-in it just came through, rather than a bare form.
 */
import { FormEvent, useState } from 'react';
import { useTranslation } from 'react-i18next';

import { supabase } from '../lib/supabase';
import {
  MIN_PASSWORD_LENGTH,
  PasswordProblem,
  validateNewPassword,
} from '../lib/passwordPolicy';
import LoginLayout from './LoginLayout';
import PasswordField from './PasswordField';

/** Spelled out rather than built from the problem name, so every message key
 *  in this file can be grepped for in the locale bundles. */
const PROBLEM_MESSAGE: Record<PasswordProblem, string> = {
  tooShort: 'password.errTooShort',
  looksProvisioned: 'password.errLooksProvisioned',
  mismatch: 'password.errMismatch',
};

interface Props {
  /** The signed-in account's email, so the user can see whose password this is. */
  email: string | null;
  /** Called once the password is changed AND the flag cleared; parent reloads. */
  onDone: () => void;
}

export default function ChangePasswordGate({ email, onDone }: Props) {
  const { t } = useTranslation();
  const [password, setPassword] = useState('');
  const [confirm, setConfirm] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const submit = async (e: FormEvent) => {
    e.preventDefault();
    const problem = validateNewPassword(password, confirm);
    if (problem) {
      setError(t(PROBLEM_MESSAGE[problem], { min: MIN_PASSWORD_LENGTH }));
      return;
    }
    setBusy(true);
    setError(null);

    const { error: pwErr } = await supabase.auth.updateUser({ password });
    if (pwErr) {
      setError(t('password.errApi', { message: pwErr.message }));
      setBusy(false);
      return;
    }

    // The password is already changed by this point. If clearing the flag
    // fails, saying "could not change your password" would be a lie that sends
    // the user back to a password that no longer works — so the message says
    // what actually happened and which password to use next.
    const { error: flagErr } = await supabase.rpc('clear_password_change_flag');
    if (flagErr) {
      setError(t('password.errFlag'));
      setBusy(false);
      return;
    }

    setBusy(false);
    onDone();
  };

  return (
    <LoginLayout>
      <div className="login-head">
        <h2>{t('password.gateTitle')}</h2>
        <p>{t('password.gateSub')}</p>
      </div>

      {email ? <div className="pwgate-note">{t('password.signedInAs', { email })}</div> : null}

      {error ? (
        <div className="login-err">
          <span className="msym" aria-hidden="true">
            error
          </span>
          <span>{error}</span>
        </div>
      ) : null}

      <form className="login-form" onSubmit={(e) => void submit(e)}>
        <label htmlFor="new-password">
          <span>{t('password.newLabel')}</span>
          <PasswordField
            id="new-password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            autoComplete="new-password"
            disabled={busy}
            required
          />
        </label>
        <label htmlFor="confirm-password">
          <span>{t('password.confirmLabel')}</span>
          <PasswordField
            id="confirm-password"
            value={confirm}
            onChange={(e) => setConfirm(e.target.value)}
            autoComplete="new-password"
            disabled={busy}
            required
          />
        </label>
        <p className="pwgate-hint">{t('password.hint', { min: MIN_PASSWORD_LENGTH })}</p>
        <button type="submit" className="login-cta" disabled={busy || !password || !confirm}>
          {busy ? <span className="login-spinner" aria-hidden="true" /> : null}
          <span>{busy ? t('password.saving') : t('password.cta')}</span>
        </button>
      </form>

      {/* The only way out other than setting a password. scope: 'local' ends
          this browser's session only, matching AppShell's sign-out. */}
      <button
        type="button"
        className="pwgate-signout"
        disabled={busy}
        onClick={() => void supabase.auth.signOut({ scope: 'local' })}
      >
        {t('password.signOut')}
      </button>
    </LoginLayout>
  );
}
